Import( 'project' )
Import( 'libs' )

import os.path

libraries = [ libs.openfxHack,
			  libs.tuttleHost,
              libs.boost_filesystem,
			  libs.dl,
			  libs.boost_gil,
			  libs.png,
			 ]

project.Program( project.getName(), dirs=['src'], libraries=libraries, installDir=os.path.join(project.inOutputBin(),'example') )

