Import( 'project' )
Import( 'libs' )

project.createOfxPlugin( dirs = ['src'],
                         libs = [ libs.boost_system,
						          libs.openfxHack,
								  libs.openfxPluginSupportHack,
								  libs.tuttlePlugin,
								  libs.boost_gil
                                 ] )

