Import( 'project', 'libs' )

project.createOfxPlugin(
	dirs = ['src'],
	includes = ['src/dpx-google-code/libdpx'],
	libs = [
		libs.tuttlePlugin,
		libs.boost_gil,
		libs.boost_filesystem,
		libs.boost_regex,
		]
	)

