Import( 'project', 'libs' )

project.createOfxPlugin( dirs = ['src'],
                         libs = [
                                 libs.tuttlePlugin,
                                 libs.ctl,
                                 libs.boost_filesystem,
                                 ] )

