Import( 'project' )
Import( 'libs' )

project.createOfxPlugin( dirs = ['src'],
                         libraries = [ libs.openfxHack,
                                  libs.openfxPluginSupportHack,
                                  libs.tuttlePlugin,
                                  libs.boost_gil,
                                  libs.boost_filesystem,
                                  libs.openjpeg,
								  libs.boost_regex,
                                 ] )

