Import( 'project' )
Import( 'libs' )

project.createOfxPlugin( sources = project.scanFiles( ['src'] ),
                         libs = [libs.openfxHack,
                                 libs.openfxPluginSupportHack,
                                 libs.tuttlePlugin,
                                 libs.boost_gil,
                                 libs.boost_system,
                                 ] )

