Import( 'project' )
Import( 'libs' )

project.createOfxPlugin( dirs = ['src'],
                         libs = [
								  libs.tuttlePlugin,
								  libs.openexr,
								  libs.boost_gil,
								  libs.boost_filesystem,
								  libs.boost_regex,
                                 ] )

