Import('project', 'libs')

project.createOfxPlugin(
	dirs=['src'],
	includes=['src'],
	libraries=[
		libs.tuttlePlugin,
		libs.openexr,
		libs.boost_gil,
		libs.boost_filesystem,
		libs.boost_regex,
		]
	)

