Import( 'project' )
Import( 'libs' )

project.createOfxPlugin( dirs = ['src'],
                         libs = [ libs.openfxHack,
								  libs.openfxPluginSupportHack,
								  libs.tuttlePlugin,
								  libs.openexr,
								  libs.boost_gil,
								  libs.boost_filesystem,
                                 ] )

