Import( 'project' )
Import( 'libs' )

libraries = [ libs.openfxHack,
			  libs.tuttleHost,
              libs.boost_filesystem,
			  libs.boost_regex,
			  libs.boost_program_options,
			  libs.dl,
			  libs.boost_gil,
			 ]

name = project.getName()
sourcesDir = 'src'
samCheckSources = project.scanFiles( [sourcesDir] )

samCheckEnv = project.createEnv( libraries )
samCheckEnv.Append( CPPPATH=sourcesDir )
samCheck = samCheckEnv.Program( target=name, source=samCheckSources )

samCheckInstall = samCheckEnv.Install( project.inOutputBin(), samCheck )
samCheckEnv.Alias( name, samCheckInstall )
samCheckEnv.Alias( 'all', samCheckInstall )



