Import( 'project', 'libs' )
import os

installDir = project.inOutputDir('python/example')

sourcesFiles = project.scanFiles( ".", accept=['*.py'] )

install = project.env.Install(installDir, sourcesFiles)

project.env.Alias('all', install)
