Import( 'project' )
Import( 'libs' )

project.createOfxPlugin( dirs = ['src'],
                         libs = [
                                 libs.tuttlePlugin,
                                 libs.boost_gil,
                                 libs.boost_system,
								 libs.caca
                                 ] )

