Import( 'project', 'libs' )
import os.path

project.Program(
	project.getName(),
	dirs = ['src'],
	libraries = [
		libs.openfxHack,
		libs.terry,
		libs.boost_gil,
		libs.png,
		libs.tuttleCommon,
		libs.boost_filesystem,
		libs.boost_thread,
		libs.boost_log,
		],
	installDir = os.path.join(project.inOutputBin(),'example')
	)

