Import( 'project', 'libs' )

project.UnitTest(
	target = project.getDirs([-3,-1]),
	dirs = ['.'],
	includes=[project.getRealAbsoluteCwd('#libraries/tuttle/src')], # temporary solution
	libraries = [
		libs.terry,
		libs.boost_unit_test_framework,
		]
	)

