Import( 'project', 'libs' )

libraries = [libs.tuttleHost,
             libs.boost_unittestframework]

testEnv = project.createEnv( libraries )
unittest = testEnv.UnitTest( target=project.getDirs([-3,-1]), source=project.scanFiles( ['.'] ) )

