Import( 'project' )
Import( 'libs' )

libraries = [libs.boost_system,
             libs.boost_filesystem,
			 libs.dl,
			 libs.openfxHack,
			 libs.tuttleHost,
			 libs.boost_gil,
			 ]

sourcesDir = 'src'
samSources = project.scanFiles( [sourcesDir] )

samEnv = project.createEnv( libraries )
samEnv.Append( CPPPATH=sourcesDir )
sam = samEnv.Program( target=project.getName(), source=samSources )

samInstall = samEnv.Install( project.inOutputBin(), sam )
samEnv.Alias('all', samInstall )



