Import( 'project', 'libs' )

project.StaticLibrary(
		'openfxPluginSupportHack',
		dirs=['Library'],
		includes=['include', '#libraries/tuttle/src/'], # temporary...
		libraries=[libs.openfxHack, libs.boost],
		shared=True
	)

