Import( 'project' )
Import( 'libs' )

print 'openfxPluginSupportHack'

project.StaticLibrary( 'openfxPluginSupportHack',
                       dirs=['Library'],
                       includes=['include'],
                       libraries=[libs.openfxHack, libs.boost],
                       shared=True
                      )

