Import( 'project', 'libs' )

project.createOfxPlugin(
	dirs = ['src'],
	libraries = [
		libs.tuttlePlugin,
		libs.terry,
		libs.boost_gil,
		libs.openimageio,
		libs.boost_filesystem,
		libs.boost_regex,
		libs.half,
		]
	)

