Import( 'project' )
Import( 'libs' )

libraries = [ libs.boost_serialization,
              #libs.tuttleHost,
              libs.boost_unittestframework]


testEnv = project.createEnv( libraries )
unittest = testEnv.UnitTest( target=project.getName(), source=project.scanFiles( ['.'] ) )

