Import( 'project', 'libs' )

project.ScriptTests(
		target = project.getDirs(2),
		dirs = ['.'],
		libraries = [libs._tuttle],
		procEnvFlags = {
			'PYTHONPATH': project.inOutputDir('python'),
			'OFX_PLUGIN_PATH': project.inOutputPlugin(),
			},
	)

