Import( 'project', 'libs' )

project.UnitTest(
	target = project.getDirs([-3,-1]),
	dirs = ['.'],
	libraries = [
		libs.tuttleTest,
		],
	execLibraries = [
		libs.pluginJpeg,
		libs.pluginPng,
		libs.pluginExr,
		libs.pluginInvert,
		libs.pluginMerge,
		libs.pluginCrop,
		libs.pluginBlur,
		],
	)

