import os.path
Import( 'project' )
Import( 'libs' )

libraries = [ libs.openfxHack,
			  libs.tuttleHost,
              libs.boost_filesystem,
			  libs.dl,
			  libs.boost_gil,
			 ]

name = project.getName()
sourcesDir = 'src'
samSources = project.scanFiles( [sourcesDir] )

samEnv = project.createEnv( libraries )
samEnv.Append( CPPPATH=sourcesDir )
sam = samEnv.Program( target=name, source=samSources )

outputDir = os.path.join(project.inOutputBin(),'example')
samInstall = samEnv.Install( outputDir, sam )
samEnv.Alias(name, samInstall )
samEnv.Alias('all', samInstall )



