Import( 'project' )
Import( 'libs' )

project.createOfxPlugin( dirs = ['src'],
                         libs = [
                                 libs.tuttlePlugin,
                                 libs.gl,
                                 ] )

