Import( 'project' )
Import( 'libs' )

libraries = [ libs.openfxHack,
			  libs.tuttleHost,
              libs.boost_filesystem,
              libs.boost_system,
              libs.boost_program_options,
              libs.boost_regex,
			 ]

project.Program( project.getName(), dirs=['src'], libraries=libraries )
