#!/usr/bin/python
import os
import sys
import subprocess

currentDir  = os.getcwd()

red='\033[0;31m'
RED='\033[1;31m'
blue='\033[0;34m'
BLUE='\033[1;34m'
green='\033[0;32m'
GREEN='\033[1;32m'
cyan='\033[0;36m'
CYAN='\033[1;36m'
NC='\033[0;0m'  # No Color

args = sys.argv
args.pop(0)

showHelp = False;
showBrief = False;
verbose = False;

if( len( args ) == 0 ):
	showHelp = True;

for arg in args:
	if( arg == "-h" or arg == "--help" ):
		showHelp=True;
	if( arg == "--brief"):
		showBrief=True;

if( showHelp ):
	print( BLUE + 'TuttleOFX project [http:/ / sites.google.com/site/tuttleofx]' + NC );
	print( '' );
	print( BLUE + 'NAME' + NC );
	print( GREEN + '\tsam-viewer - view images or sequences' + NC );
	print( '' );
	print( BLUE + 'SYNOPSIS' + NC );
	print( GREEN + '\tsam-viewer [directory - file - sequence]' );
	print( GREEN + '\tsam-viewer specificReader [directory - file - sequence]' );
	print( '' );
	print( BLUE + 'DESCRIPTION' + NC );
	print( '' );
	print( 'Viewer for sequences and files.' + NC );
	print( '' );
	print( BLUE + 'OPTIONS' + NC );
	print( '' );
	print( '  -h [ --help ]           display help' );
	print( '  --brief                 display a brief summary of the tool' );
	print( '' );
	exit();

if( showBrief ):
	print( GREEN + 'viewer of file/sequence' + NC );
	exit();

TUTTLE_ROOT = os.getenv('TUTTLE_ROOT')

if( TUTTLE_ROOT == None ):
	print( RED + 'error : TUTTLE_ROOT is not set.' + NC );
	exit();

if( not os.path.exists( TUTTLE_ROOT+'/.tuttleofx' )):
	os.mkdir( TUTTLE_ROOT+'/.tuttleofx' )

os.environ['TUTTLE_HOME']=TUTTLE_ROOT+'/.tuttleofx'
os.environ['LD_LIBRARY_PATH']= TUTTLE_ROOT+'/lib'
os.environ['PATH']= TUTTLE_ROOT+'/bin'
os.environ['SAM_PATH']=TUTTLE_ROOT+'/bin'
os.environ['OFX_PLUGIN_PATH']=TUTTLE_ROOT+'/plugin'

TUTTLE_ROOT  = currentDir+'/dist/linux/release'


if( len(args) == 1 ):
	subprocess.call( 'sam-do reader ' + " ".join(args) + ' // viewer' , shell=True )
else:
	subprocess.call( 'sam-do ' + " ".join(args) + ' // viewer' , shell=True )
