#!/usr/bin/python

"""
Set environment and call sam-ls -ls
"""
import os
import sys
import subprocess

TUTTLE_ROOT = os.getenv('TUTTLE_ROOT')
if TUTTLE_ROOT is None:
    # sam-ls should be in TUTTLE_ROOT/bin
    CURRENT_PATH = os.path.dirname(os.path.realpath(__file__))
    os.environ['TUTTLE_ROOT'] = os.path.abspath(
                                    os.path.join(CURRENT_PATH, "..")) 

TUTTLE_HOME = os.path.join(TUTTLE_ROOT, '.tuttleofx')
if not os.path.exists(TUTTLE_HOME):
    os.mkdir(TUTTLE_HOME)

os.environ['TUTTLE_HOME'] = TUTTLE_HOME
os.environ['LD_LIBRARY_PATH'] = os.path.join(TUTTLE_ROOT, 'lib')
os.environ['PATH'] = os.path.join(TUTTLE_ROOT, 'bin')
os.environ['SAM_PATH'] = os.path.join(TUTTLE_ROOT, 'bin')

subprocess.call('sam-ls -ls ' + " ".join(sys.argv[1:]), shell=True)
