#!/usr/bin/python
import os
import sys
import subprocess

currentDir  = os.getcwd()
TUTTLE_ROOT  = currentDir+'/dist/linux/release'

if( not os.path.exists( TUTTLE_ROOT+'/.tuttleofxTest' )):
	os.mkdir( TUTTLE_ROOT+'/.tuttleofxTest' )

os.environ['TUTTLE_ROOT']= TUTTLE_ROOT 
os.environ['TUTTLE_HOME']=TUTTLE_ROOT+'/.tuttleofxTest'
os.environ['LD_LIBRARY_PATH']= TUTTLE_ROOT+'/lib'
os.environ['PATH']= TUTTLE_ROOT+'/bin'
os.environ['SAM_PATH']=TUTTLE_ROOT+'/bin'

args = sys.argv
args.pop(0)

subprocess.call( 'sam-ls -s ' + " ".join(args) , shell=True )
