Import( 'project', 'libs' )

project.createOfxPlugin(
    dirs = ['src'],
    includes = ['src'],
    libraries = [
        libs.openfxHack,
        libs.openfxPluginSupportHack,
        libs.tuttlePlugin,
        libs.boost,
        libs.boost_gil
    ] )

