Import( 'project', 'libs' )

project.createOfxPlugin( dirs = ['src'],
                         libs = [libs.openfxHack,
								 libs.openfxPluginSupportHack,
								 libs.tuttlePlugin,
								 libs.boost,
								 libs.boost_gil] )

