Import( 'project', 'libs' )

if project.env['mode'] != 'production':
	project.UnitTest(
		target = project.getDirs([-3,-1]),
		dirs = ['.'],
		libraries = [
			libs.tuttleHost,
			libs.boost_unit_test_framework,
			]
		)

