Import( 'project', 'libs' )

libraries = [libs.tuttleHost,
             libs.boost_unittestframework]

testEnv = project.createEnv( libraries )
testEnv.UnitTest( target=project.getDirs([-4,-2,-1]), source=project.scanFiles( ['.'] ) )

